### ISSUE TITLE
Two Copies of each file?

### ISSUE THREAD

**Issue by DontBelieveMe** [neon2d/neon2d#1]
Why is there a copy of the n2d and neon2d folders inside the neon2d folder. Is there a reason for this?
I Saw the commit log stating that you added files via upload, but what does this mean?

**Comment by matthewd673** [comment]
So, right after I deleted the old repo by accident I panicked and tried to upload via github.com instead of committing -> syncing. Feel free to remove duplicates & if worse comes to worse we'll revert it
