### ISSUE TITLE
A Maths Library.

### ISSUE THREAD

**Issue by DontBelieveMe** [neon2d/neon2d#11]
A maths library is needed (maybe not a full one for now, but maybe just vectors etc).
In `Shape.Line` there are 4 variables `lx1, ly1, lx2,ly2`.
This could be shortened into 2 2D vectors. Vectors are also useful generally, and are considered better practice than having lots of variables

**Comment by matthewd673** [comment]
Should Vector2 and other neon2d.Math classes by actual classes or structs?

**Comment by matthewd673** [comment]
#12 should solve this problem. Just looking for approval before merging. Until merged, lets try to avoid editing crucial files so #12 can successfully merge
