### ISSUE TITLE
Add a .gitignore

### ISSUE THREAD

**Issue by DontBelieveMe** [neon2d/neon2d#14]
This would be useful and can mean things like .suo and all the large binarys and dlls can be excluded from being commited/pushed - just commiting what is needed to create a build (.sln's, project files, source files, images etc)
This also might solve some commit/branching conflits - or at least prevent them in the future.

**Comment by matthewd673** [comment]
Smart move, doing it now

**Comment by matthewd673** [comment]
Alright, added .gitignore based on gh's visual studio template

**Comment by DontBelieveMe** [comment]
Note: Follow instructions [Here:](http://stackoverflow.com/questions/1139762/ignore-files-that-have-already-been-committed-to-a-git-repository) to update the repository so that the gitignore removes the appropriate file. Oh, and you may want to test it in another branch - just in case.

**Comment by matthewd673** [comment]
Alrighty, doing that now
