### ISSUE TITLE
Coding standards and naming conventions.

### ISSUE THREAD

**Issue by DontBelieveMe** [neon2d/neon2d#23]
As I been going through the code I have started to notice inconsistencies between the code files. 
When I say inconsistencies I mean things like naming conventions, so I reckon that we need to decide on a standard, and stick to it - it just makes the engine more usable and easier to code in/with.
I'm happy to go with whatever, but I recommend the standard C# naming conventions - PascalCase etc.

Or perhaps look at [this](https://msdn.microsoft.com/en-gb/library/ff926074.aspx) - the offical Microsoft recommend conventions.

**Comment by matthewd673** [comment]
Along those same lines, while looking through the Scene and renderer code I noticed that while the Text class stores info about color and font, the various Shape classes don't store info on Brushes/thickness. I think removing the text class in favor of a render() function similar to the Shape's would be good.

**Comment by matthewd673** [comment]
OK, back to the naming conventions thing, this is my personal pattern:
- lowercaseUppercase() for methods
- lowercase for variables
- UppercaseUppercase for classes

**Comment by DontBelieveMe** [comment]
I would say have lowercaseUpper case for variables too, simply due the fact that it is easier to read what the variable is and what its name is.

**Comment by matthewd673** [comment]
Alright, I'll remember that going forward. As for changing the old variables, that'll take some time
