### ISSUE TITLE
Rectangle class in neon2d.Math

### ISSUE THREAD

**Issue by matthewd673** [neon2d/neon2d#24]
A way to store an x, y, width, and height in a single class in .Math would be great for Shapes, Props, and Sprites.

**Comment by DontBelieveMe** [comment]
Why cant we just use `Physics.Rect`?

**Comment by matthewd673** [comment]
I suppose we could do that, it would allow for built in collisions. I'll add the overloads now

**Comment by DontBelieveMe** [comment]
Or we could add an `AABB`class into math? Its more math'ey' and doesn't allow for rotations, as `Physics.Rect` will eventually do.

**Comment by matthewd673** [comment]
You're welcome to add that if you wish. As it is I'm midway through adding support for Physics.Rect, but I think an AABB will be needed in the long run
