### ISSUE TITLE
Ints or Floats?

### ISSUE THREAD

**Issue by DontBelieveMe** [neon2d/neon2d#27]
What should we use as the type for storing locations and dimensions and stuff... Ints or Floats. I've always used Floats for the accuracy and being able to go half's and stuff. Ints on the other hand, don't have as much accuracy but seem simpler.

**Comment by matthewd673** [comment]
Floats, worse comes to worse we can stick a `(int)` in front of it, like I did with the shape classes

**Comment by DontBelieveMe** [comment]
Ill do a vector2f class as well then.

**Comment by matthewd673** [comment]
Sounds good
