### ISSUE TITLE
.Circle class in neon2d.Physics

### ISSUE THREAD

**Issue by matthewd673** [neon2d/neon2d#28]
Add a circle class with collisions in the Physics class, I'm thinking about doing it like this (once I'm back at my home PC): (pseudo code) 

```
public Circle(center, radius) //maybe overload for diameter instead of radius

bool intersecting(other)
{
if(distance between points is less than radius) { return true }
}
```

**Comment by matthewd673** [comment]
I'm beginning work right now in a new pull, in keeping with the shortened rectangle name (`Rect`) I'm calling this one `Circ`

**Comment by DontBelieveMe** [comment]
I would keep it at `Circle`. `Rect` is a common shortage of `Rectange` because rectangle is long. `Circ` is not as common. What's the point in loosing 2 letters to ambuguity?

**Comment by matthewd673** [comment]
Fair enough
