### ISSUE TITLE
[Long-Term] Hardware Rendering.

### ISSUE THREAD

**Issue by DontBelieveMe** [neon2d/neon2d#45]
As in using DirectX or OpenGL (Or Vulkan) to drastically speed up rendering.
Obviously this a very long term goal, but could be very beneficial.
Preferably this could be changed at runtime (So if an editor was made then it would be easier to change the Renderer).
If you like I could start working on this, but it may take ages...

**Comment by matthewd673** [comment]
In this kind of situation I would much prefer OpenGL over DirectX. I think this is a good goal to work towards long term, but I don't intend to actively work on this right now. I do know of a good C# wrapper for OpenGL: [OpenTK](http://www.opentk.com/) so maybe we can use this when we finally rewrite.

**Comment by DontBelieveMe** [comment]
Thats good as I have a lot more experience with OpenGL. 
OpenTK is the framework that I have worked with in the past and is more C#'y (Object Orientated etc..). 
I think it also has support for embedding in `Form`s so could be used in an editor.

**Comment by matthewd673** [comment]
I have used it embedded in Forms before and its a super painless process. I also know of a syntax highlighted textbox, if your interested in an editor. Should be fairly simple to whip up

**Comment by matthewd673** [comment]
I've created a new repo (neon2d/neonGL) for this project. My goal is to recreate all current functionality with a different renderer, then we can see about combining them.
