### ISSUE TITLE
Redo renderer.

### ISSUE THREAD

**Issue by DontBelieveMe** [neon2d/neon2d#9]
I have been looking the code which draws stuff and (from a performance point of view) it looks less than optimal. 
For example there's a massive loop in the main render function and there's lots of conditional branching statements. 
I am not at my pc right now, but I will look at this later.

**Comment by matthewd673** [comment]
I agree with you whole heatedly. Additionally, around the time of pull #5 I think it was rendering glitches presented themselves once more. Any ideas for fixing this? My only idea is turning off a for-loop the first time it hits a null, so it can move on to the others. It would be nice to have a struct for everything in scene so we could have 1 list, 1 loop, and shapes wouldn't render on top of images automatically.

**Comment by DontBelieveMe** [comment]
I also think this is when we want to solidly decide on the renderer structure. I.e do you want every object to have its own render function (object.render') or have a standalone renderer (be able to push objects, and to render them all in a big function call.

**Comment by matthewd673** [comment]
How would a single render function work? Let it take Text, or Line, or Prop, etc. or what?

**Comment by DontBelieveMe** [comment]
![untitled](https://cloud.githubusercontent.com/assets/10855194/13582040/da700a06-e4a1-11e5-8eb2-46b8505e23e6.png)
So have a `Renderer`class with an overloaded `Push()` function. This function will take the object to be drawn as its parameter.
So:
&nbsp;&nbsp;&nbsp;&nbsp;`Renderer.Push(Text textObject);`
&nbsp;&nbsp;&nbsp;&nbsp;`Renderer.Push(Line lineObject);`
&nbsp;&nbsp;&nbsp;&nbsp;`Renderer.Push(Prop propObject);`
&nbsp;&nbsp;&nbsp;&nbsp;etc....

It will then add these objects to lists which can be iterated over and drawn when the `Renderer.render()` function is called.

**Comment by matthewd673** [comment]
Should we separate the renderer from the scene though? I kind of like the idea of the scene being the input/output part of the window. Besides, one less class (we would need to keep scene and make renderer or change to input & renderer) if we combine renderer & the existing scene.

**Comment by DontBelieveMe** [comment]
Or have one master `Renderer`for everything and being able to add `Scene`s to the `Renderer`.
I.e.
&nbsp;&nbsp;&nbsp;&nbsp;`Renderer.AddScene(Scene scene);`
And then adding the objects to the `Scene`and not the `Renderer`directly.
For example:
&nbsp;&nbsp;&nbsp;&nbsp;`Scene.Push(Prop propObject);`
And the `Renderer`will use the objects added to the scene?

**Comment by matthewd673** [comment]
I'm going to modify the existing Scene in a new branch, but if it turns out bad it should be a minor fix switching things around.

**Comment by matthewd673** [comment]
Alright, pull #13 is the new place to work on this (push commits to branch new-renderer-#9 please!) Before we get too into this I'm going to merge #12 (branch math-review) to keep things from getting out of hand

**Comment by matthewd673** [comment]
Scene class is completely modified, I could probably push it now. I'm going to try with a separate branch again to keep things tidy.
